### PR TITLE
Modify README.md again

### PR DESCRIPTION
**Pull request by HarshKapadia2**
- I changed the text.

### CODE REVIEW

**Comment by SirusCodes** [comment]
Why are you making such PR for hacktoberfest never expected this from you....

**Comment by HarshKapadia2** [comment]
LOL. I haven't even registered for Hacktoberfest.

**Comment by SirusCodes** [comment]
> LOL. I haven't even registered for Hacktoberfest.

WHYYYYY 😮

**Comment by HarshKapadia2** [comment]
No time.

**Pull request closed without merging**
